### ISSUE TITLE
USER STORY: Chat with other runners in a forum

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/love-running#1]
In order to **feel like a part of a community** as a **user**, I can **chat with other runners in a moderated forum**

## Acceptance Criteria

* The forum should be easy for the user to find
* The user should receive notifications when there are new forum comments
* The forum should have a moderator, who administrates and encourages conversations

## Tasks

- [ ] Create section for forum on same page as ideas section
- [ ] Attach commentor's user name to show who made each comment
- [ ] Update page after every comment is submitted
- [ ] Create notifier so that users are made aware when new comments are submitted
- [ ] Test functionality
