### ISSUE TITLE
USER STORY: Anonymous ideas section for users

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/love-running#2]
In order to **improve the experience of the entire group** as an **administrator**, I can **collect feedback via an anonymous ideas section**

## Acceptance Criteria

* The feedback should be available for all users to read, but the author of each comment should remain anonymous
*  The section should be simple to operate by minimizing the number of steps it takes to submit ideas

## Tasks

- [ ] Create new page on the site for ideas section
- [ ] Create text input and submit button for the idea info
- [ ] Test the functionality
