### ISSUE TITLE
USER STORY: Option to create a username

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/love-running#3]
In order to **easily engage with all features** as a **user**, I can **create a username**

## Acceptance Criteria

* Users should be prompted to create a username and login
* Users should be given the option to be remembered on their current device
* Users should be allowed to edit their username

## Tasks

- [ ] Create login screen on home page
- [ ] Create possibility to edit username if desired
- [ ] Integrate username into all interactive features so users can see who they are interacting with
- [ ] Test functionality
