### ISSUE TITLE
USER STORY: Ability to log in as a guest

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/love-running#4]
In order to **navigate through the website without interacting** as an **unregistered user**, I can **choose to log in as a guest**

## Acceptance Criteria

* The option should appear when login screen is prompted
* The option should be clearly marked and easy for the user to select

## Tasks

- [ ] Create 'login as a guest' button for users
- [ ] Place button in easy to find place on the login screen
- [ ] Allow user to navigate website anonymously after logging in as guest
- [ ] Test functionality
