### ISSUE TITLE
USER STORY: Add recipe section to promote a healthy diet for users

### ISSUE THREAD

**Issue by craigdickerson725** [craigdickerson725/love-running#5]
In order to **further the health benefits of the site** as an **administrator**, I can **add a recipe section to give users ideas for healthy meal options**

## Acceptance Criteria

* The recipe section should contain healthy meal recipes that are accessible for all users
* The section should contain images that demonstrate what the prepared meal should look like
* The section should contain a comments section which allow users to share and rate the meals

## Tasks

- [ ] Collect recipes from various open source cookbooks
- [ ] Add the HTML and CSS for the section to the same page as the user forum
- [ ] Create comments section for user interaction
- [ ] Test functionality
